=== Politecnico-JIC/HechosHistoricos/HechosHistoricos.dtd
<!ELEMENT HechosHistoricos (HechosHistorico+)>
        <!ELEMENT HechosHistorico (Fecha, Epoca?,PersonajeDestacado*)?>
        <!ELEMENT Epoca  (Epoca1 | Epoca2)?>
        <!ELEMENT Epoca1 (#PCDATA) >
        <!ELEMENT Epoca2 (#PCDATA) >
        <!ELEMENT PersonajeDestacado ANY >
        <!ELEMENT Nombre ANY >
        <!ELEMENT FechaNacimiento (#PCDATA) >
        <!ELEMENT Fecha (#PCDATA  |FormatoFecha)*>
        <!ELEMENT FormatoFecha (Dia, mes , Año)>
        <!ELEMENT Dia (#PCDATA)>
        <!ELEMENT mes (#PCDATA)>
        <!ELEMENT Año (#PCDATA)>
        <!ATTLIST  HechosHistorico descripcion CDATA #REQUIRED>

=== Politecnico-JIC/HechosHistoricos/HechosHistoricos.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
<!DOCTYPE HechosHistoricos [
        <!ELEMENT HechosHistoricos (HechosHistorico)>
            <!ELEMENT HechosHistorico (Fecha)>
        <!ELEMENT Fecha (Dia, mes , A単o) >
        <!ELEMENT Dia (#PCDATA)>
        <!ELEMENT mes (#PCDATA)>
        <!ELEMENT A単o (#PCDATA)>
        <!ATTLIST  HechosHistorico descripcion CDATA #REQUIRED>
        ]>

        -->

<!DOCTYPE HechosHistoricos SYSTEM "HechosHistoricos.dtd">
<HechosHistoricos>
    <HechosHistorico descripcion = "">
        <Fecha>
            <FormatoFecha>
            <Dia></Dia>
            <mes></mes>
            <A単o></A単o>

            </FormatoFecha>


        </Fecha>
        <Epoca>
            <Epoca1></Epoca1>
        </Epoca>

        <PersonajeDestacado>
            Test persona <Nombre></Nombre> y fecha de nacimiento <FechaNacimiento></FechaNacimiento>
        </PersonajeDestacado>

    </HechosHistorico>
    <HechosHistorico descripcion = "">
        <Fecha>
            2022-10-09




        </Fecha>
        <Epoca>
            <Epoca2></Epoca2>
        </Epoca>
        <PersonajeDestacado> </PersonajeDestacado>

    </HechosHistorico>


</HechosHistoricos>
